export const HERO_MOBILE_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAPklEQVR4nAEzAMz/APzk8v73w+//ysHl/6Gxy/4AzLTz/9yN8f9pTZ3/ABdM/wAsQJT+GilH/yovRP8EEzv+ov4e9XwR1vEAAAAASUVORK5CYII=";
export const HERO_TABLET_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAPklEQVR4nAEzAMz/AP7w9//6zvL/083q/7XC1P8AyLvz/9SM6/9gS5f/ABlJ/wAyUKD+EiNB/x8nO/8CEjT+shEfLVw7xZMAAAAASUVORK5CYII=";
export const HERO_DESKTOP_BLUR =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAPklEQVR4nAEzAMz/AP7w9v/6z/L/1M3r/7bD1f8AyLry/9SM6/9gS5b/ABlJ/wAzUaH+ESI//x4mO/8CEjX+sm4fLV1KUJkAAAAASUVORK5CYII=";
